# Generated by Django 6.0.4 on 2026-05-01 08:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='term_years',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of years for the subscription term.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Term (Years)'),
        ),
        migrations.AlterField(
            model_name='member',
            name='con',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CBU'),
        ),
        migrations.AlterField(
            model_name='member',
            name='initial_paid_up',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Auto-filled from CBU. Editable.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='member',
            name='initial_subscription',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Auto-computed as Subscription × Term. Editable.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='member',
            name='subscription',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Annual subscription amount.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
