# Generated by Django 6.0.4 on 2026-05-01 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_member_term_years_alter_member_con_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='cbu_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, help_text='Auto-computed: CBU minus annual subscription. Saved to DB.', max_digits=12, verbose_name='CBU Balance'),
        ),
        migrations.AlterField(
            model_name='member',
            name='con',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Capital Build-Up — original contribution amount.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CBU'),
        ),
    ]
