# Generated by Django 6.0.4 on 2026-05-01 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_member_cbu_balance_alter_member_con'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='initial_paid_up',
        ),
        migrations.RemoveField(
            model_name='member',
            name='initial_subscription',
        ),
    ]
