# Generated by Django 6.0.4 on 2026-05-01 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_remove_member_initial_paid_up_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='cbu_balance',
        ),
    ]
