# Generated by Django 6.0.4 on 2026-05-02 02:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_remove_member_cbu_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='initial_paid_up',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Initial paid-up amount — automatically added to CBU on first save.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Initial Paid-Up'),
        ),
        migrations.AlterField(
            model_name='member',
            name='con',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Capital Build-Up — total accumulated contribution.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CBU'),
        ),
    ]
