# Generated by Django 6.0.4 on 2026-05-02 03:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_member_initial_paid_up_alter_member_con'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='base_con',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Original CBU contribution entered by the admin.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Base CBU'),
        ),
        migrations.AlterField(
            model_name='member',
            name='con',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, help_text='Auto-computed: Base CBU + Initial Paid-Up.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CBU'),
        ),
        migrations.AlterField(
            model_name='member',
            name='initial_paid_up',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Always added on top of Base CBU whenever saved.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Initial Paid-Up'),
        ),
    ]
