# Generated by Django 6.0.4 on 2026-05-02 03:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_member_base_con_alter_member_con_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='base_con',
        ),
        migrations.RemoveField(
            model_name='member',
            name='initial_paid_up',
        ),
        migrations.AlterField(
            model_name='member',
            name='con',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Capital Build-Up — original contribution amount.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CBU'),
        ),
    ]
