# Generated by Django 6.0.4 on 2026-05-02 03:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_remove_member_base_con_remove_member_initial_paid_up_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='initial_paid_up',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount to add on top of the current CBU each time this is updated.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Initial Paid-Up'),
        ),
        migrations.AlterField(
            model_name='member',
            name='con',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Capital Build-Up — accumulated total of all paid-up contributions.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CBU'),
        ),
    ]
