# Generated by Django 6.0.4 on 2026-05-03 03:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_member_initial_paid_up_alter_member_con'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='savings',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Member savings amount.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='member',
            name='con',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Capital Build-Up. Admin can set this directly, and initial_paid_up adds on top.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CBU'),
        ),
        migrations.AlterField(
            model_name='member',
            name='initial_paid_up',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount to add on top of the CBU value submitted in the form.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Initial Paid-Up'),
        ),
    ]
