# Generated by Django 6.0.4 on 2026-05-03 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0011_membertransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivated_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='member',
            name='deactivation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='deactivation_reason',
            field=models.CharField(blank=True, choices=[('non_payment', 'Non-payment of dues/subscription'), ('voluntary_withdrawal', 'Voluntary withdrawal'), ('expired_term', 'Membership term expired'), ('violation', 'Violation of cooperative policies'), ('death', 'Death of member'), ('inactivity', 'Prolonged inactivity'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='deactivation_reason_other',
            field=models.CharField(blank=True, help_text='Custom reason when "Other" is selected', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='deactivation_resolution',
            field=models.TextField(blank=True, help_text='Action plan or requirements needed for reactivation', null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='reactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reactivated_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='member',
            name='reactivation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='reactivation_notes',
            field=models.TextField(blank=True, help_text='Notes about the reactivation process', null=True),
        ),
        migrations.AlterField(
            model_name='membertransaction',
            name='type',
            field=models.CharField(choices=[('initial_paid_up', 'Initial Paid-Up'), ('cbu', 'CBU Deposit'), ('savings', 'Savings Deposit'), ('subscription', 'Subscription Payment')], max_length=20),
        ),
    ]
