# Generated by Django 4.1.13 on 2026-05-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0012_member_deactivated_by_member_deactivation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='account_number',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
