# Generated by Django 4.1.13 on 2026-05-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0013_alter_member_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
