# Generated by Django 4.1.13 on 2026-05-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0014_alter_member_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='deactivation_reason',
            field=models.CharField(blank=True, choices=[('non_payment', 'Non-payment of dues/subscription'), ('voluntary_withdrawal', 'Voluntary withdrawal'), ('expired_term', 'Membership term expired'), ('violation', 'Violation of cooperative policies'), ('death', 'Deceased'), ('inactivity', 'Prolonged inactivity'), ('awol', 'Absence without official leave'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
