# Generated by Django 4.1.13 on 2026-05-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0015_alter_member_deactivation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='membertransaction',
            name='term_years',
            field=models.PositiveSmallIntegerField(blank=True, help_text='If set, updates the member term when type is subscription.', null=True),
        ),
    ]
