# Generated by Django 6.0.4 on 2026-05-01 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='administrator',
            table='administrator',
        ),
    ]
