# Generated by Django 6.0.4 on 2026-05-01 09:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_alter_administrator_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('member_add', 'Member Added'), ('member_edit', 'Member Edited'), ('member_delete', 'Member Deleted'), ('member_view', 'Member Viewed'), ('login', 'Admin Login'), ('logout', 'Admin Logout'), ('export', 'Data Exported'), ('other', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger')], default='info', max_length=10)),
                ('target_name', models.CharField(blank=True, help_text='Human-readable target, e.g. member name', max_length=200)),
                ('target_id', models.CharField(blank=True, help_text='Account number or PK of the affected object', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Log',
                'verbose_name_plural': 'Admin Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
