# Generated by Django 4.1.13 on 2026-05-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_adminlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminlog',
            name='severity',
        ),
        migrations.AddField(
            model_name='adminlog',
            name='status',
            field=models.CharField(choices=[('viewed', 'Viewed'), ('updated', 'Updated'), ('deleted', 'Deleted')], default='viewed', max_length=10),
        ),
    ]
