# Generated by Django 4.1.13 on 2026-05-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_remove_adminlog_severity_adminlog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='status',
            field=models.CharField(choices=[('viewed', 'Viewed'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('added', 'Added')], default='viewed', max_length=10),
        ),
    ]
