# Generated by Django 6.0.4 on 2026-05-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_alter_adminlog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='status',
            field=models.CharField(choices=[('viewed', 'Viewed'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('added', 'Added'), ('session_start', 'Session Started'), ('session_end', 'Session Ended')], default='viewed', max_length=20),
        ),
    ]
